### PR TITLE
Added ManagerUser Page

### PR DESCRIPTION
**Pull request by duc-beluga**
I made a lot of changes in this branch. Both backend and frontend
+ verifyJWT:

1. I used REFRESH_TOKEN_SECRET instead of ACCESS_TOKEN_SECRET 
(The only token is stored in cookies is refreshToken)
2. I removed Header "Authorization" check 
(Cookies are flagged with HttpOnly (browser default behavior for security reason). Therefore, I cannot access token from the cookie in the frontend and pass it into the request header. ('Authorization': 'Bearer <accessToken>'). Cookie extraction can only be done is the backend.)

+ added EmployeeTable
+ added ExistingEmployeePage
+ added Route in index.js

image

I also notice that in the registerEmployee page, it's asking for the "FirstName" and "LastName", however, Employee schema doesn't have those attributes.

### CODE REVIEW

**Comment by duc-beluga** [comment]
Added Reset Password feature and Delete Employee feature:
BizBiz

**Comment by mengzhuou** [comment]
Good job! 
Seems like there's a parsing error so I pushed a commit for that. You just need to have a bit of revision:

1. New password requirement#1 fails:
image
2. #2 fails.
image

I didn't check for others but make sure this branch has these password requirements covered, you can set it up all in the frontend, please use the error handler from RegisterClient to make our style consistent!
image

**Comment by mengzhuou** [comment]
1. Make sure that "Your Password Has Been Updated Successfully" does not exist in the same time with another warning message.
image
Based on our conversation, these are the detailed requirements to implement in this branch:
2. Let's refactor the backend code to return the user-role after logged in, and display the role "Employee" or "Manager" on the top left of the top navbar.
3. The employee is not able to see the Management button in the front end at all. If employee tries to access the management page through the URL, it should return a “403 unauthorized page" which is something we already had in the backend. You just need to wire it up with that one. 
image

**Comment by duc-beluga** [comment]
Logged In as Employee:
image

Logged In as Manager:
image

Update successfully:
image

Fail requirements:
image
image
image
image

**Review by mengzhuou — APPROVED** [review]

**Pull request merged**
