### PR TITLE
Story login function

### PR DESCRIPTION
**Pull request by KaiHackney**
user is able to be created, logged in, logged out, and if they have data it can be accessed using tokens. This was done following the MERN tutorial

### CODE REVIEW

**Comment by KaiHackney** [comment]
Screenshot 2023-09-26 at 5 56 15 PM
Screenshot 2023-09-26 at 6 02 49 PM
Screenshot 2023-09-26 at 5 55 36 PM
Screenshot 2023-09-26 at 5 55 51 PM
Screenshot 2023-09-26 at 5 55 57 PM
Screenshot 2023-09-26 at 6 01 47 PM
Screenshot 2023-09-26 at 5 58 28 PM
Screenshot 2023-09-26 at 5 56 43 PM

**Comment by KaiHackney** [comment]
post: http://localhost:3500/auth
get: http://localhost:3500/auth/refresh
post: http://localhost:3500/auth/logout
get: http://localhost:3500/auth/refresh

{
    "username": "NShaina",
    "password": "123123123"
}

**Comment by KaiHackney** [comment]
node

require('crypto').randomBytes(64).toString('hex')

**Comment by KaiHackney** [comment]
ACCESS_TOKEN_SECRET=
REFRESH_TOKEN_SECRET=

**Comment by mengzhuou** [comment]
image
Register function requires auth

**Comment by KaiHackney** [comment]
I have added a register function to auth, this will allow anyone to create a user in order to test out functionality. as seen in the image from postman last week the headers for content-type and authorization are necessary, but for users actions, authorization is needed, this can be done by adding a header titled "Authorization" and in the field next to it adding "Bearer " and whatever the generated access token for the user is

**Pull request closed without merging**
