### PR TITLE
Added TailwindCSS and deleteClient function

### PR DESCRIPTION
**Pull request by duc-beluga**
Currently, the function is able to remove a client based on provided ID in /:id. 
Later on, we add edit this to remove clients based on 'filter' (name, email,...).

### CODE REVIEW

**Review by mengzhuou — CHANGES_REQUESTED** [review]
Can you add some screenshots about testing it in the Postman and anything related? More details can be found under "Coding Convention for User Story" in the important announcement google doc.

**Comment by duc-beluga** [comment]
Sure!

image
image
image

**Comment by duc-beluga** [comment]
I forgot to create a new branch for a different story but accidentally pushed the new changes to this branch.
I edited the existingClients page, added Pagination (5 clients per page), and did some styling with daisyUI.

image

**Comment by mengzhuou** [comment]
For coding consistency, can you remove the usage of TailwindCSS? Sorry, I love it, but it's hard to manage in a team project

**Comment by duc-beluga** [comment]
No worries, I'll remove the tailwindCSS

**Pull request closed without merging**
