### PR TITLE
Login function new

### PR DESCRIPTION
**Pull request by KaiHackney**
This is the updated login function PR updated to main

### CODE REVIEW

**Comment by mengzhuou** [comment]
image

1. Is your UI page looking like this? Let's have login page locate inside component folder: 
image

2. What username and password do i need to login?

**Comment by KaiHackney** [comment]
fixed #1
for #2 you will need to open postman and run auth/register with an account for it to be in the system, if youd like I can upload images or I can just go over with you on tuesday

**Comment by mengzhuou** [comment]
> fixed #1 for #2 you will need to open postman and run auth/register with an account for it to be in the system, if youd like I can upload images or I can just go over with you on tuesday

Yeah please, any images will be helpful if it's related to postman testing. Thank you ;)

**Comment by KaiHackney** [comment]
Screenshot 2023-10-16 at 11 51 08 AM

Content: http://localhost:3500/auth/register

{    
    "username": "Username",
    "password": "Password",
    "roles": ["Employee"]
}


Username and Password can be filled with whatever user you would like to add

**Review by mengzhuou — APPROVED** [review]

**Pull request merged**
